apiVersion: apps/v1 
kind: StatefulSet
metadata: 
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    component: mongodb
    tier: DB
spec:
  selector:
    matchLabels:
      project: roboshop
      component: mongodb
      tier: DB
  replicas: 1
  serviceName: "mongodb-headless"
  template:
    metadata:
      labels:
        project: roboshop
        component: mongodb
        tier: DB
    spec:
      containers:
      - name: mongodb
        image: "{{ .Values.statefulset.imageURL }}:{{ .Values.statefulset.imageVersion }}"
        volumeMounts:
        - name: monogdb-sc-pvc
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: monogdb-sc-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: ebs-sc
      resources:
        requests:
          storage: 2Gi
