apiVersion: v1 
kind: Service
metadata:
  name: user
  namespace: roboshop
  labels:
    project: roboshop
    component: user
    tier: app
spec:
  selector:
    project: roboshop
    component: user
    tier: app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080