apiVersion: v1 
kind: Service
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    component: mysql
    tier: DB
spec:
  selector:
    project: roboshop
    component: mysql
    tier: DB
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306