apiVersion: v1 
kind: Service
metadata:
  name: redis-headless
  namespace: roboshop
  labels:
    project: roboshop
    component: redis
    tier: DB
spec:
  clusterIP: None
  selector:
    project: roboshop
    component: redis
    tier: DB
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379