apiVersion: v1 
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    component: shipping
    tier: app
data:
  CART_ENDPOINT: "cart:8080" 
  DB_HOST: "mysql"