apiVersion: v1 
kind: Service
metadata:
  name: rabbitmq-headless
  namespace: roboshop
  labels:
    project: roboshop
    component: rabbitmq
    tier: DB 
spec:
  clusterIP: None
  selector:
    project: roboshop
    component: rabbitmq
    tier: DB 
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672