apiVersion: v1 
kind: Service
metadata:
  name: frontend
  namespace: roboshop
spec:
  type: LoadBalancer
  selector:
    component: frontend
    project: roboshop
    tier: web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080